// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWv1OKx-0tFR7c0ADLdb3sP1tV9r1-Lw',
    appId: '1:429378688516:web:f39f9e9ac542c151388751',
    messagingSenderId: '429378688516',
    projectId: 'weftweb',
    authDomain: 'weftweb.firebaseapp.com',
    storageBucket: 'weftweb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgIBrLuQyJwDMHNvDVzIUT257bbHxZw6U',
    appId: '1:429378688516:android:e0e900a34827f480388751',
    messagingSenderId: '429378688516',
    projectId: 'weftweb',
    storageBucket: 'weftweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIp74VFP9dZEHtDlGH7LCRUkrQXkPt1A8',
    appId: '1:429378688516:ios:28ced1553e27ed39388751',
    messagingSenderId: '429378688516',
    projectId: 'weftweb',
    storageBucket: 'weftweb.firebasestorage.app',
    iosBundleId: 'com.example.frontendWeft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIp74VFP9dZEHtDlGH7LCRUkrQXkPt1A8',
    appId: '1:429378688516:ios:28ced1553e27ed39388751',
    messagingSenderId: '429378688516',
    projectId: 'weftweb',
    storageBucket: 'weftweb.firebasestorage.app',
    iosBundleId: 'com.example.frontendWeft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeWv1OKx-0tFR7c0ADLdb3sP1tV9r1-Lw',
    appId: '1:429378688516:web:4ad1d84206912934388751',
    messagingSenderId: '429378688516',
    projectId: 'weftweb',
    authDomain: 'weftweb.firebaseapp.com',
    storageBucket: 'weftweb.firebasestorage.app',
  );
}